### ISSUE TITLE
ghc-prim creates a single file package.conf.inplace file which GHC 7.10 rejects

### ISSUE THREAD

**Issue by tel** [ghcjs/ghcjs-boot#15] opened 2015-04-02 18:05 UTC
Not sure why it does this. Is it using an older version of Cabal somewhere?

I can locate that `package.conf.inplace` file at `~/.ghcjs/x86_64-darwin-0.1.0-7.10.1/ghcjs/ghcjs-boot/boot/ghc-prim/dist/package.conf.inplace`.

```
In order, the following would be installed:
ghc-prim-0.4.0.0 (new package)
/Users/tel/.ghcjs/x86_64-darwin-0.1.0-7.10.1/ghcjs/ghcjs-boot$ [cabal]: /Users/tel/.cabal/bin/cabal "--config-file" "/Users/tel/.ghcjs/x86_64-darwin-0.1.0-7.10.1/ghcjs/cabalBootConfig" "install" "./boot/ghc-prim" "--solver=topdown" "--global" "--ghcjs" "--one-shot" "--avoid-reinstalls" "--builddir" "dist" "--with-compiler" "/Users/tel/bin/ghcjs" "--with-hc-pkg" "/Users/tel/bin/ghcjs-pkg" "--prefix" "/Users/tel/.ghcjs/x86_64-darwin-0.1.0-7.10.1/ghcjs" "--enable-documentation" "--haddock-html" "--haddock-hyperlink-source" "--enable-library-profiling" "--root-cmd" "/Users/tel/.ghcjs/x86_64-darwin-0.1.0-7.10.1/ghcjs/run.sh"
/Users/tel/.cabal/bin/cabal --config-file /Users/tel/.ghcjs/x86_64-darwin-0.1.0-7.10.1/ghcjs/cabalBootConfig install ./boot/ghc-prim --solver=topdown --global --ghcjs --one-shot --avoid-reinstalls --builddir dist --with-compiler /Users/tel/bin/ghcjs --with-hc-pkg /Users/tel/bin/ghcjs-pkg --prefix /Users/tel/.ghcjs/x86_64-darwin-0.1.0-7.10.1/ghcjs --enable-documentation --haddock-html --haddock-hyperlink-source --enable-library-profiling --root-cmd /Users/tel/.ghcjs/x86_64-darwin-0.1.0-7.10.1/ghcjs/run.sh
Warning: No remote package servers have been specified. Usually you would have
one specified in the config file.
Resolving dependencies...
[1 of 1] Compiling Main             ( boot/ghc-prim/dist/setup/setup.hs, boot/ghc-prim/dist/setup/Main.o )

boot/ghc-prim/dist/setup/setup.hs:19:1: Warning:
    Module ‘System.Cmd’ is deprecated: Use "System.Process" instead
Linking ./boot/ghc-prim/dist/setup/setup ...
Configuring ghc-prim-0.4.0.0...
Building ghc-prim-0.4.0.0...
Preprocessing library ghc-prim-0.4.0.0...
ghcjs-0.1.0-7.10.1.bin: ghc no longer supports single-file style package databases (dist/package.conf.inplace) use 'ghc-pkg init' to create the database with the correct format.
Failed to install ghc-prim-0.4.0.0
cabal: Error: some packages failed to install:
ghc-prim-0.4.0.0 failed during the building phase. The exception was:
ExitFailure 1
ghcjs-boot: error running: /Users/tel/.cabal/bin/cabal --config-file /Users/tel/.ghcjs/x86_64-darwin-0.1.0-7.10.1/ghcjs/cabalBootConfig install ./boot/ghc-prim --solver=topdown --global --ghcjs --one-shot --avoid-reinstalls --builddir dist --with-compiler /Users/tel/bin/ghcjs --with-hc-pkg /Users/tel/bin/ghcjs-pkg --prefix /Users/tel/.ghcjs/x86_64-darwin-0.1.0-7.10.1/ghcjs --enable-documentation --haddock-html --haddock-hyperlink-source --enable-library-profiling --root-cmd /Users/tel/.ghcjs/x86_64-darwin-0.1.0-7.10.1/ghcjs/run.sh
exit status: 1
stderr: Warning: No remote package servers have been specified. Usually you would have
one specified in the config file.

boot/ghc-prim/dist/setup/setup.hs:19:1: Warning:
    Module ‘System.Cmd’ is deprecated: Use "System.Process" instead
ghcjs-0.1.0-7.10.1.bin: ghc no longer supports single-file style package databases (dist/package.conf.inplace) use 'ghc-pkg init' to create the database with the correct format.
cabal: Error: some packages failed to install:
ghc-prim-0.4.0.0 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by luite** [comment] 2015-04-02 18:28
Has been fixed in The cabal 1.22 branch (and master) unfortunately the fix
did not make it into ghc 7.10.1

**Comment by tel** [comment] 2015-04-02 18:39
Ah, ah. Cabal HEAD would have it?

**Comment by luite** [comment] 2015-04-02 18:43
Yes,  but don't get the master branch since that gets you Cabal 1.23, get
the cabal-1.22 branch

**Comment by tonyday567** [comment] 2015-04-12 08:56
Reproduced this with ghc 7.10.1 and with the 1.22 branch of cabal.
I wasn't sure if 1.22 branch referred to the submodule in ghcjs-boot or my `cabal` executable, so I upgraded both.

Also worked around #14, with:

    ghcjs-boot --dev --ghcjs-boot-dev-branch prim-fix --ghcjs-boot-dev-repo https://github.com/tonyday567/ghcjs-boot.git

**Comment by luite** [comment] 2015-04-12 09:25
Bump the Cabal version number for the library you install with GHC 7.10 to make sure it does not pick the one from the global package db.

(Stage1 of the boot process, which is everything before Cabal, uses GHC to compile Setup.hs scripts, so it's GHC's Cabal lib that has to be upgraded)

**Comment by tonyday567** [comment] 2015-04-13 02:31
ok, I forgot about the library Cabal.  I found that the cabal executable ("cabal-install") needed to be built with the 1.22 branch as well.
Using the 1.22 branch fixed #14 as well.
Thanks

**Comment by jiyinyiyong** [comment] 2015-04-19 17:17
`ghc` and `cabal` installed with Homebrew on OS X is still `7.10.1` and `1.20.0.1`. Keep getting this in installing. >_<

**Comment by hamishmack** [comment] 2017-07-08 00:45
I presume if this is not fixed already in `master` it should be working in `ghc-8.0`

**Closed by hamishmack** 2017-07-08 00:45 UTC
